/**
 * Phase 2 codegen — turns the `GET /api/projects/{projectId}/functions/_metadata`
 * response into a typed `functions.types.ts` file. Each export's
 * `argsJsonSchema` is compiled to a TypeScript interface via
 * `json-schema-to-typescript`; the result is hoisted as
 * `${Module}_${Export}_Args`. The emitted `Functions` interface maps
 *   module → exportName → FunctionRef<Args, unknown>
 * so the SDK's `createClient<DB, Functions>` generic gives callers fully
 * typed `db.functions.<module>.<name>(args)` signatures.
 *
 * `TResult` stays `unknown` for Phase 2 — return-type metadata lands in
 * Phase 3 once the runtime starts emitting it from `__metadata`.
 */

import { compile, type JSONSchema } from "json-schema-to-typescript";

export interface FunctionExportMeta {
  /** Export name (e.g. `"list"`). */
  name: string;
  /** Tagged kind — `"query" | "mutation" | "action"`. */
  kind: "query" | "mutation" | "action";
  /** JSON Schema for the `args` payload. */
  argsJsonSchema: JSONSchema;
}

export interface FunctionMeta {
  /** Server-side function id (filesystem key). */
  id: string;
  /** Module name — first path segment of the function URL. */
  name: string;
  runtimeShape: "v1" | "v2" | string;
  exports: FunctionExportMeta[];
  lastDeployedAt: string;
}

export type FunctionsMetadataResponse = FunctionMeta[];

const COMPILE_OPTS = {
  bannerComment: "",
  declareExternallyReferenced: false,
  enableConstEnums: false,
  format: false,
  strictIndexSignatures: false,
};

/** Capitalize first letter; rest unchanged. Used for type-name segments. */
function pascalSegment(s: string): string {
  if (s.length === 0) return s;
  return s[0]!.toUpperCase() + s.slice(1);
}

/** Lowercase + sanitize a path segment for use in a generated type name. */
function safeSegment(s: string): string {
  return s.replace(/[^A-Za-z0-9_]/g, "_");
}

/** `${Module}_${Export}_Args` — generated arg type name. */
function argsTypeName(moduleName: string, exportName: string): string {
  return `${pascalSegment(safeSegment(moduleName))}_${pascalSegment(safeSegment(exportName))}_Args`;
}

/**
 * Compile each export's `argsJsonSchema` to TS. `json-schema-to-typescript`
 * emits a single `export interface <Name> { ... }` per call; we just
 * concatenate them. Schemas with no properties still produce a valid (empty)
 * interface.
 */
async function emitArgInterfaces(metadata: FunctionsMetadataResponse): Promise<string> {
  const chunks: string[] = [];
  for (const fn of metadata) {
    for (const exp of fn.exports) {
      const name = argsTypeName(fn.name, exp.name);
      // json-schema-to-typescript respects the schema's `title` for the
      // emitted interface name — set it explicitly so the output matches
      // what the Functions interface references below.
      const schema: JSONSchema = { ...exp.argsJsonSchema, title: name };
      const rendered = (await compile(schema, name, COMPILE_OPTS)).trim();
      chunks.push(rendered);
    }
  }
  return chunks.join("\n\n");
}

/**
 * Emit the `Functions` interface body — module → export → FunctionRef.
 * Modules with no exports render as `module: {};`.
 */
function emitFunctionsInterface(metadata: FunctionsMetadataResponse): string {
  const lines: string[] = ["export interface Functions {"];
  for (const fn of metadata) {
    if (fn.exports.length === 0) {
      lines.push(`  ${fn.name}: {};`);
      continue;
    }
    lines.push(`  ${fn.name}: {`);
    for (const exp of fn.exports) {
      const t = argsTypeName(fn.name, exp.name);
      lines.push(`    ${exp.name}: FunctionRef<${t}, unknown>;`);
    }
    lines.push("  };");
  }
  lines.push("}");
  return lines.join("\n");
}

/**
 * Render the full `functions.types.ts` body. Imports `FunctionRef` from
 * `@excalibase/sdk` so callers can pass `Functions` as the second generic to
 * `createClient`.
 */
export async function emitFunctionsTypes(metadata: FunctionsMetadataResponse): Promise<string> {
  const argInterfaces = await emitArgInterfaces(metadata);
  const functionsInterface = emitFunctionsInterface(metadata);

  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by @excalibase/sdk codegen — do not edit.");
  lines.push("// Run `npx excalibase-codegen functions` to regenerate.");
  lines.push("");
  lines.push('import type { FunctionRef } from "@excalibase/sdk";');
  lines.push("");
  if (argInterfaces.length > 0) {
    lines.push(argInterfaces);
    lines.push("");
  }
  lines.push(functionsInterface);
  lines.push("");
  return lines.join("\n");
}

export async function generateFunctionsFile(
  metadata: FunctionsMetadataResponse,
): Promise<string> {
  return emitFunctionsTypes(metadata);
}
